let DATA=null;
const fmt=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const when=s=>{if(!s)return '—';const d=new Date(s);return d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});};
const mile=(p,k)=>p.milestones?.[k]?.views ?? '—';
function affClass(v){return v>=60?'good':v<=40?'bad':''}
function render(){const d=DATA;if(!d)return;document.getElementById('updatedAt').textContent=`Обновлено ${when(d.meta.generated_at)} · ${d.meta.timezone}`;document.getElementById('profilePill').textContent=`Square · ${d.posts.length} постов`;document.getElementById('modeLabel').textContent=d.meta.learning_only?'Learning only':'Adaptive ON';
 const o=d.overview,b=o.best_post;const cards=[['Постов за 24ч',o.posts_24h,'последние публикации'],['Просмотры 24ч',fmt(o.views_on_24h_posts),'на постах последних 24ч'],['Медиана 6ч+',fmt(o.median_views_6h_plus),'зрелые публикации'],['Breakouts',`${o.posts_300_plus}/${o.posts_500_plus}/${o.posts_1000_plus}`,'300+ / 500+ / 1000+'],['Лучший пост',b?`$${esc(b.symbol)} · ${fmt(b.views)}`:'—',b?when(b.published_at):'нет данных']];document.getElementById('kpis').innerHTML=cards.map(x=>`<div class="kpi"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');
 document.getElementById('recentPosts').innerHTML=d.posts.slice(0,8).map(p=>`<div class="post-row"><div class="ticker">$${esc(p.symbol||'—')}</div><div class="post-copy"><b>${esc((p.text||'').split('\n')[0]||'Публикация')}</b><span>${esc(p.lane)} · ${when(p.published_at)}</span></div><div class="post-views"><b>${fmt(p.views)}</b><small>views</small></div></div>`).join('');
 const ts=d.learning.tickers.slice(0,8),max=Math.max(60,...ts.map(x=>x.affinity));document.getElementById('topSymbols').innerHTML=ts.map(x=>`<div class="bar-item"><b>$${esc(x.symbol)}</b><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,x.affinity/max*100)}%"></div></div><div class="bar-val">${fmt(x.affinity)}</div></div>`).join('')||'<span>Нужно больше зрелых постов.</span>';
 renderHours();renderPosts();renderSymbols();renderLearning();renderOutcomes();}
function renderHours(){const rows=DATA.learning.hours||[],map=new Map(rows.map(x=>[x.hour,x])),mx=Math.max(55,...rows.map(x=>x.affinity));document.getElementById('hourStrip').innerHTML=[...Array(24)].map((_,h)=>{const r=map.get(h),v=r?.affinity??25;return `<div class="hour-col" title="${h}:00 · affinity ${r?fmt(r.affinity):'—'} · n=${r?.posts||0}"><div class="hour-bar" style="height:${Math.max(4,v/mx*95)}%"></div><span>${h}</span></div>`}).join('');document.getElementById('timingBars').innerHTML=[...Array(24)].map((_,h)=>{const r=map.get(h)||{affinity:50,posts:0,median_views:0};return `<div class="timing-row"><b>${String(h).padStart(2,'0')}:00</b><div class="bar-track"><div class="bar-fill" style="width:${Math.max(2,r.affinity)}%"></div></div><span>med ${fmt(r.median_views)}</span><b class="affinity ${affClass(r.affinity)}">${fmt(r.affinity)}</b></div>`}).join('');}
function renderPosts(){const q=(document.getElementById('postSearch')?.value||'').toLowerCase(),lane=document.getElementById('laneFilter')?.value||'';const rows=DATA.posts.filter(p=>(!lane||p.lane===lane)&&(!q||`${p.symbol} ${p.text}`.toLowerCase().includes(q)));document.getElementById('postsBody').innerHTML=rows.map(p=>`<tr><td class="post-cell"><a target="_blank" rel="noopener" href="https://www.binance.com/en/square/post/${encodeURIComponent(p.post_id)}">$${esc(p.symbol||'—')}</a><span>${esc((p.text||'').replace(/\s+/g,' '))}</span></td><td><span class="lane">${esc(p.lane)}</span></td><td>${when(p.published_at)}</td><td><b>${fmt(p.views)}</b></td><td>${mile(p,'30m')}</td><td>${mile(p,'2h')}</td><td>${mile(p,'6h')}</td><td>${mile(p,'24h')}</td><td>${fmt(p.likes)} ♥ · ${fmt(p.comments)} 💬</td></tr>`).join('');}
function renderSymbols(){document.getElementById('symbolsBody').innerHTML=(DATA.learning.tickers||[]).map(r=>`<tr><td><b>$${esc(r.symbol)}</b></td><td>${r.posts}</td><td>${fmt(r.median_views)}</td><td>${fmt(r.avg_views)}</td><td>${fmt(r.breakout_rate)}%</td><td>${fmt(r.absolute_300_rate)}%</td><td><b class="affinity ${affClass(r.affinity)}">${fmt(r.affinity)}</b></td></tr>`).join('');}
function renderLearning(){const l=DATA.learning;document.getElementById('learningStats').innerHTML=`Режим: <strong>${l.learning_only?'LEARNING_ONLY':'ADAPTIVE'}</strong><br>Зрелых образцов: <strong>${l.mature_samples}</strong><br>Медиана 24ч: <strong>${fmt(l.account_median_24h)}</strong><br><br>Affinity <strong>${l.learning_only?'не влияет':'мягко влияет'}</strong> на выбор: тикер + час + lane + breakout, с exploration и saturation-защитой.`;const rows=l.lanes||[],mx=Math.max(60,...rows.map(x=>x.affinity));document.getElementById('laneStats').innerHTML=rows.map(x=>`<div class="bar-item"><b>${esc(x.lane)}</b><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,x.affinity/mx*100)}%"></div></div><div class="bar-val">${fmt(x.affinity)}</div></div>`).join('')||'Пока мало зрелых данных.';const a=l.authors||[],am=Math.max(60,...a.map(x=>x.affinity));document.getElementById('authorStats').innerHTML=a.map(x=>`<div class="bar-item"><b>${esc(x.author)}</b><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,x.affinity/am*100)}%"></div></div><div class="bar-val">${x.posts} · ${fmt(x.affinity)}</div></div>`).join('')||'Новые авторские данные появятся после публикаций v11.';}

function renderOutcomes(){const o=DATA.outcomes||{total:0,entered:0,active:0,closed:0,tp1_hits:0,tp3_hits:0,stops:0,target_complete:0,tp1_rate:0,tp3_rate:0,followups:0,recent:[]};const cards=[['Tracked setups',o.total,'только с публичными целями'],['Активные',o.active,'pending entry + active'],['TP1 hit rate',`${fmt(o.tp1_rate)}%`,`${o.tp1_hits}/${o.entered||0} вошедших`],['TP3 hit rate',`${fmt(o.tp3_rate)}%`,`${o.tp3_hits}/${o.entered||0} вошедших`],['Follow-ups',o.followups,`${o.target_complete} завершены по целям · ${o.stops} stop`]];const k=document.getElementById('outcomeKpis');if(k)k.innerHTML=cards.map(x=>`<div class="kpi"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');const body=document.getElementById('outcomesBody');if(!body)return;body.innerHTML=(o.recent||[]).map(t=>{const h=t.hits||{},exp=(t.exposed_targets||[]).map(x=>x.toUpperCase()).join(' / ')||'—',fs=(t.followups||[]).map(x=>x.target_name?`${x.target_name.toUpperCase()} · ${when(x.published_at)}`:`${x.kind} · ${when(x.published_at)}`).join('<br>')||'—';const mark=v=>v?'<span class="hit">✓</span>':'—';return `<tr><td><b>$${esc(t.symbol||'—')}</b><br><span class="lane">${esc((t.direction||'').toUpperCase())}</span><br><small>${when(t.published_at)}</small></td><td><b>${esc(t.status||'—')}</b><br><small>${esc(t.close_reason||'')}</small></td><td>${esc(exp)}</td><td>${mark(h.tp1)}</td><td>${mark(h.tp2)}</td><td>${mark(h.tp3)}</td><td>${h.stop?'<span class="stop-hit">✓</span>':'—'}</td><td>${fs}</td></tr>`}).join('')||'<tr><td colspan="8">Outcome Engine начнёт заполняться после публикации поста с явно указанной ценой цели.</td></tr>';}
async function load(){try{const r=await fetch(`data.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);DATA=await r.json();render()}catch(e){document.getElementById('updatedAt').textContent=`Не удалось загрузить data.json: ${e.message}`;}}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active');document.getElementById('pageTitle').textContent=b.textContent;}));document.getElementById('refreshBtn').addEventListener('click',load);document.getElementById('postSearch').addEventListener('input',renderPosts);document.getElementById('laneFilter').addEventListener('change',renderPosts);load();
