name: Binance Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache last published symbol
        uses: actions/cache@v3
        with:
          path: last_published.txt
          key: last-published-${{ github.run_id }}
          restore-keys: |
            last-published-

      - run: pip install -r requirements.txt

      - run: python main.py
        env:
          MISTRAL_API: ${{ secrets.MISTRAL_API }}
          SQUARE_API: ${{ secrets.SQUARE_API }}
